services:
  redis:
    image: redis:latest
    container_name: redis-rate-limiter
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  goapp:
    build: .
    container_name: go-rate-limiter
    depends_on:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - .:/app

volumes:
  redis_data:
    driver: local